# Generated by Django 5.2.10 on 2026-01-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_user_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount_paise',
            new_name='total_amount_inr',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price_paise',
            new_name='unit_price_inr',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_in_paise',
            new_name='price_in_inr',
        ),
    ]
